name: Send Code as ZIP and Create Release

on:
  push:
    branches:
      - main

jobs:
  send-zip-and-create-release:
    runs-on: ubuntu-latest

    steps:
      # בדיקה החוצה את הקוד למכונת העבודה
      - name: Checkout code
        uses: actions/checkout@v3

      # יצירת קובץ ZIP של הקוד
      - name: Create ZIP archive
        run: |
          zip -r repository.zip .

      # שליחת הקובץ כ-HTTP POST ל-API
      - name: Send ZIP to API
        run: |
          curl -X POST https://example.com/api/upload \
          -H "Content-Type: multipart/form-data" \
          -F "file=@repository.zip"

      # יצירת Release חדש
      - name: Create a Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: "This release was automatically created after pushing to the main branch."
          draft: false
          prerelease: false
